#!/bin/sh

if ! wifi-connect-gui; then
  exit 1
fi

i=0
while [ "$i" -le 20 ] && ! wifi-connected; do
  pkill -USR1 -u "$(id -u)" i3status
  # pkill -RTMIN+3 -u "$(id -u)" i3blocks
  i=$((i + 1))
  sleep 1
done

pkill -USR1 -u "$(id -u)" i3status
# pkill -RTMIN+3 -u "$(id -u)" i3blocks
